### ISSUE TITLE
How about trans it into Flow Launcher?

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [abbasou/PowerToysRunPluginBitwarden#1]
About this: https://www.flowlauncher.com/docs/#/port-plugins?id=woxpowertoys-run-c-plugins

PTRun work well, but not support custom search, and can't search bookmark, Flow Launcher is an another way.

**Comment by abbasou** [comment]
You are correct. For our purposes with this plugin, Flow Launcher is further developed. In fact, I've already switched over to Flow Launcher from PTRun. I'm not a developer so I cannot contribute much to this effort. There is some discussion and investigation happening on a BW plugin for FL already, but I'm just patiently waiting for progress updates.
